### ISSUE TITLE
error in removing watermark

### ISSUE THREAD

**Issue by chungimungi** [m3at/video-watermark-removal#9]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/chedi/aiisc/VideoFusion/mets.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:04.00, start: 0.000000, bitrate: 582 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 256x256, 580 kb/s, 8 fps, 8 tbr, 16384 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
[FRAME]
pkt_dts_time=N/A
[SIDE_DATA]
side_data_type=H.26[45] User Data Unregistered SEI message
[/SIDE_DATA]
[/FRAME]
[FRAME]
pkt_dts_time=N/A
[/FRAME]

https://github.com/m3at/video-watermark-removal/assets/90822297/1c4b67da-ae3f-42ad-aeda-382545922d3b

i have added the  video as well

_Originally posted by @chungimungi in https://github.com/m3at/video-watermark-removal/issues/8#issuecomment-2169170410_

**Comment by m3at** [comment]
Thanks for sharing the output.

If you look at the command results you posted, you can see that there is no keyframe being extracted (`pkt_dts_time=N/A`). This is because this video is too short, there is no need for keyframes.  
The simple script in this repo use keyframes, so there is nothing to work on. 

If you really want to, you can just extract every frames and process that instead, it will technically work but the output will likely be bad.  
This video look AI generated, so I would suggest instead to tune your prompt, for example adding "watermark" as a negative.

---

_Side note: please don't duplicated comments_

**Comment by chungimungi** [comment]
yes thank you !
